# Site settings
baseURL = "https://hugo-huerealvarado-lbs.netlify.app/"
languageCode = "en-us"
title = "Hugo's Portfolio for Data Analytics"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Hugo Huere Alvarado"
  description = "MSc Financial Analysis 2021 Student at London Business School"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Hugo Huere Alvarado"
    subtitle = "Data Analytics"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"
      
    #[[params.navigation.links]]
      #name = "About me"
      #url = "about"
      
    [[params.navigation.links]]
      name = "My projects"
      url = "projects"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    #[[params.navigation.button1]]
      #name = "Get Started"
      #url = "blogs"

    # Button Style 2
    #[[params.navigation.button2]]
     # name = "Log In"
      #url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title =  "Welcome to my website"
    subtitle = "My portfolio of data analytics projects developed at London Business School"
    buttonText = "Get Started"

  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "AIRBNB MEXICO CITY"
      subtitle = "How much will a couple spend to stay four nights in Mexico City?"
      image = "MXN.jpg"
      url = "projects/project1"

    [[params.tiles.showcase]]
      title = "COVID-19 STATISTICS"
      subtitle = "Analysis by co-morbidities and ICU admission"
      image = "COVID-19.jpg"
      url = "projects/project2"

    [[params.tiles.showcase]]
      title = "STEVEN SPIELBERG VS TIM BURTON"
      subtitle = "Who has got the best IMDB ratings?"
      image = "IMDB.jpg"
      url = "projects/project3"

    [[params.tiles.showcase]]
      title = "2016 US PRESIDENTIAL ELECTIONS"
      subtitle = "California contributors by candidate"
      image = "US_pres.jpg"
      url = "projects/project4"

    #[[params.tiles.showcase]]
      #title = "Consequat"
      #subtitle = "Ipsum Dolor Sit Amet"
      #image = "pic05.jpg"
      #url = "blogs/ipsum"

    #[[params.tiles.showcase]]
      #title = "Etiam"
      #subtitle = "Feugiat Amet Tempus"
      #image = "pic06.jpg"
      #url = "blogs/ipsum"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "About me"
    subtitle = "Currently, reading for the Master in Financial Analysis (MFA) at London Business School. I am a 22-year-old first-generation university graduate from Milan with Peruvian roots and working experience in Frankfurt where I was engaged in the investment banking (M&A) field. Next to a genuine interest in different aspects of finance, I have a relevant international exposure and a global mindset that are matched by practical communication skills in four European languages, i.e. Italian, Spanish, English and German."
    buttonText = "Download CV"
    url = "blogs/CV/CV_Hugo Huere Alvarado.pdf"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
     formEmail = "hugoh.mfa2021@london.edu"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "hugoh.mfa2021@london.edu"

    [[params.contact.phone]]
    title = "Phone"
    phone = "UK: +44 (0)77 2313 2115"

    [[params.contact.phone]]
    phone = "IT: +39 333 614 7274"
    
    [[params.contact.address]]
    title = "Address"
    name = "London Business School"
    street = "Regents Park"
    city = "London - NW1 4SA"
    country = "United Kingdom"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Hugo Huere Alvarado & Co. ltd"

    # Uses font awesome icons
    [[params.footer.social]]
      #icon = "fa-twitter"
      #url= "https://www.twitter.com"
      #label = "Twitter"

    [[params.footer.social]]
      #icon = "fa-facebook"
     #url= "https://www.facebook.com"
      #label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/hugoboss.7/"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://github.com/Hugo-Huere-Alvarado"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/hugo-huere-alvarado-129559135/"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
